# Notebook 01 — EDA & Data Preparation

**Module:** ITI113 Machine Learning & Operations  
**Focus Area:** A — Data & EDA (Section 2 below) + C — MLOps / Data Pipeline (everything else)  
**Estimated Runtime:** 2-5 minutes

---

## What this notebook does

1. Loads the crypto scam dataset and uploads the raw file to S3
2. Exploratory Data Analysis — **placeholder, Royston's section (Focus A)**
3. Runs the data pipeline inline (text cleaning, engineered indicator features, TF-IDF, stratified train/test split) — self-contained like the tutor's notebook, so no repo clone / `utils` import is needed to run this in SageMaker Studio
4. Saves the processed train/test data and the fitted TF-IDF vectorizer to S3 for Notebook 02/03

## Dataset

- Local copy: `data/crypto_scam_dataset.csv` (already in this repo)
- Source: [Kaggle — Crypto Scam Dataset](https://www.kaggle.com/datasets/theeyanyan/crypto-scam-dataset/data), as cited in the project proposal
- 10,000 rows, columns `id`, `platform`, `text`, `label` (`scam` / `legit`), no missing values

> **Adapted for team03 (Ong Hui Lin, Student 2 — MLOps & Deployment) from the ITI113 course template notebook `01_eda_and_data_preparation.ipynb`.** The tutor's notebook mixes two things: EDA/insights (individually graded as Focus A — Royston's) and data loading/preparation (the MLOps data pipeline — this project's job). **Section 2 (EDA) is intentionally left as a placeholder for Royston to fill in** rather than written on his behalf. Everything else follows the tutor's structure as closely as the data allows, adapted to text data (TF-IDF) instead of tabular clinical features. Data cleaning and feature engineering are written **inline in this notebook**, the same way the tutor's own notebook is self-contained, rather than imported from `utils/preprocessing.py` — this notebook now runs standalone in SageMaker Studio with no repo clone required. Sections marked **`# ADAPTED`** explain what had to change.
>
> **Trade-off:** `utils/preprocessing.py` (used by Notebook 02 and the Streamlit app) has this same cleaning/feature logic. Keeping this notebook's inline copy and that file in sync is now a manual step — if the cleaning or feature-engineering logic ever changes, update both places, or the app's predictions could drift from what the model was actually trained on.

In [1]:
# After running, restart the kernel before continuing if packages were upgraded.
%pip install --upgrade --force-reinstall "sagemaker>=2,<3" boto3 botocore
!pip install -q -U 'kagglehub'

Collecting sagemaker<3,>=2
  Using cached sagemaker-2.257.5-py3-none-any.whl.metadata (19 kB)

Collecting boto3

  Downloading boto3-1.43.62-py3-none-any.whl.metadata (6.6 kB)

Collecting botocore
  Downloading botocore-1.43.62-py3-none-any.whl.metadata (5.6 kB)

Collecting attrs<26,>=24 (from sagemaker<3,>=2)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)

Collecting cloudpickle>=2.2.1 (from sagemaker<3,>=2)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)

Collecting docker (from sagemaker<3,>=2)
  Using cached docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)

Collecting fastapi (from sagemaker<3,>=2)
  Downloading fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)

Collecting google-pasta (from sagemaker<3,>=2)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting graphene<4,>=3 (from sagemaker<3,>=2)

  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting importlib-metadata<7.0,>=1.4.0 (from sagemaker<3,>=2)
  Using cached importlib_metadata-6.11.0-py3-none-any.whl.metadata (4.9 kB)

Collecting jsonschema (from sagemaker<3,>=2)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)

Collecting numpy<3.0,>=1.26.4 (from sagemaker<3,>=2)
  Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)

Collecting omegaconf<3,>=2.2 (from sagemaker<3,>=2)
  Using cached omegaconf-2.3.1-py3-none-any.whl.metadata (4.5 kB)
Collecting packaging<25,>=23.0 (from sagemaker<3,>=2)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)

Collecting pandas>=2.3.0 (from sagemaker<3,>=2)
  Using cached pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)

Collecting pathos (from sagemaker<3,>=2)
  Using cached pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Collecting platformdirs (from sagemaker<3,>=2)
  Using cached platformdirs-4.11.0-py3-none-any.whl.metadata (5.5 kB)

Collecting protobuf<7.0,>=3.12 (from sagemaker<3,>=2)
  Using cached protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)

Collecting psutil (from sagemaker<3,>=2)
  Using cached psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)

Collecting pytz (from sagemaker<3,>=2)
  Using cached pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)

Collecting pyyaml>=6.0.1 (from sagemaker<3,>=2)
  Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting requests (from sagemaker<3,>=2)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)

Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3,>=2)
  Using cached sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)
Collecting schema (from sagemaker<3,>=2)
  Using cached schema-0.7.8-py2.py3-none-any.whl.metadata (34 kB)

Collecting smdebug-rulesconfig==1.0.1 (from sagemaker<3,>=2)
  Using cached smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl.metadata (943 bytes)
Collecting tblib<4,>=1.7.0 (from sagemaker<3,>=2)
  Using cached tblib-3.2.2-py3-none-any.whl.metadata (27 kB)

Collecting tqdm (from sagemaker<3,>=2)
  Using cached tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Collecting urllib3<3.0.0,>=1.26.8 (from sagemaker<3,>=2)

  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting uvicorn (from sagemaker<3,>=2)
  Downloading uvicorn-0.52.0-py3-none-any.whl.metadata (6.6 kB)

Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Using cached jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)

Collecting s3transfer<0.20.0,>=0.19.0 (from boto3)
  Using cached s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)

Collecting graphql-core<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3,>=2)
  Using cached graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3,>=2)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)

Collecting typing-extensions<5,>=4.7.1 (from graphene<4,>=3->sagemaker<3,>=2)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting zipp>=0.5 (from importlib-metadata<7.0,>=1.4.0->sagemaker<3,>=2)
  Using cached zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)

Collecting antlr4-python3-runtime==4.9.* (from omegaconf<3,>=2.2->sagemaker<3,>=2)
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)

Collecting pydantic<3.0.0,>=2.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)

Collecting rich<15.0.0,>=13.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)

  Using cached rich-14.3.4-py3-none-any.whl.metadata (18 kB)
Collecting mock<5.0,>4.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached mock-4.0.3-py3-none-any.whl.metadata (2.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->sagemaker<3,>=2)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)

Collecting referencing>=0.28.4 (from jsonschema->sagemaker<3,>=2)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)

Collecting rpds-py>=0.25.0 (from jsonschema->sagemaker<3,>=2)
  Using cached rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)

Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)

Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)

Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)

Collecting pygments<3.0.0,>=2.13.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)

Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)

Collecting charset_normalizer<4,>=2 (from requests->sagemaker<3,>=2)
  Using cached charset_normalizer-3.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests->sagemaker<3,>=2)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting certifi>=2023.5.7 (from requests->sagemaker<3,>=2)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)

Collecting starlette>=0.46.0 (from fastapi->sagemaker<3,>=2)
  Using cached starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting annotated-doc>=0.0.2 (from fastapi->sagemaker<3,>=2)

  Using cached annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting anyio<5,>=3.6.2 (from starlette>=0.46.0->fastapi->sagemaker<3,>=2)
  Using cached anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting ppft>=1.7.8 (from pathos->sagemaker<3,>=2)

  Using cached ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Collecting dill>=0.4.1 (from pathos->sagemaker<3,>=2)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pox>=0.3.7 (from pathos->sagemaker<3,>=2)
  Using cached pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)

Collecting multiprocess>=0.70.19 (from pathos->sagemaker<3,>=2)
  Using cached multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting click>=7.0 (from uvicorn->sagemaker<3,>=2)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)

Collecting h11>=0.8 (from uvicorn->sagemaker<3,>=2)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Using cached sagemaker-2.257.5-py3-none-any.whl (1.7 MB)
Using cached smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl (20 kB)
Downloading boto3-1.43.62-py3-none-any.whl (140 kB)

Downloading botocore-1.43.62-py3-none-any.whl (15.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/15.5 MB ? eta -:--:--

   ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.8/15.5 MB 4.4 MB/s eta 0:00:04

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/15.5 MB 4.5 MB/s eta 0:00:04

   ━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/15.5 MB 4.6 MB/s eta 0:00:03

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/15.5 MB 4.6 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━ 13.9/15.5 MB 14.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 14.9/15.5 MB 12.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 11.4 MB/s  0:00:01
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)

Using cached graphql_core-3.2.11-py3-none-any.whl (214 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Using cached importlib_metadata-6.11.0-py3-none-any.whl (23 kB)
Using cached jmespath-1.1.0-py3-none-any.whl (20 kB)
Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)

Using cached omegaconf-2.3.1-py3-none-any.whl (79 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached s3transfer-0.19.2-py3-none-any.whl (90 kB)
Using cached sagemaker_core-1.0.78-py3-none-any.whl (444 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Using cached platformdirs-4.11.0-py3-none-any.whl (23 kB)

Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
Using cached rich-14.3.4-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Using cached tblib-3.2.2-py3-none-any.whl (12 kB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached annotated_types-0.8.0-py3-none-any.whl (13 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)

Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)

Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (366 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)

Using cached zipp-4.1.0-py3-none-any.whl (10 kB)
Using cached docker-7.2.0-py3-none-any.whl (148 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (224 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading fastapi-0.141.1-py3-none-any.whl (131 kB)

Using cached annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Using cached starlette-1.3.1-py3-none-any.whl (73 kB)
Using cached anyio-4.14.2-py3-none-any.whl (125 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Using cached pathos-0.3.5-py3-none-any.whl (82 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached multiprocess-0.70.19-py312-none-any.whl (150 kB)
Using cached pox-0.3.7-py3-none-any.whl (29 kB)
Using cached ppft-1.7.8-py3-none-any.whl (56 kB)
Using cached psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
Using cached pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Using cached schema-0.7.8-py2.py3-none-any.whl (19 kB)
Using cached tqdm-4.70.0-py3-none-any.whl (80 kB)

Downloading uvicorn-0.52.0-py3-none-any.whl (79 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)

Installing collected packages: schema, pytz, antlr4-python3-runtime, zipp, urllib3, typing-extensions, tqdm, tblib, smdebug-rulesconfig, six, rpds-py, pyyaml, pygments, psutil, protobuf, ppft, pox, platformdirs, packaging, numpy, mock, mdurl, jmespath, idna, h11, graphql-core, dill, cloudpickle, click, charset_normalizer, certifi, attrs, annotated-types, annotated-doc, uvicorn, typing-inspection, requests, referencing, python-dateutil, pydantic-core, omegaconf, multiprocess, markdown-it-py, importlib-metadata, graphql-relay, google-pasta, anyio, starlette, rich, pydantic, pathos, pandas, jsonschema-specifications, graphene, docker, botocore, s3transfer, jsonschema, fastapi, boto3, sagemaker-core, sagemaker
  Attempting uninstall: schema
    Found existing installation: schema 0.7.7
    Uninstalling schema-0.7.7:

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

      Successfully uninstalled schema-0.7.7
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

  Attempting uninstall: pytz
    Found existing installation: pytz 2024.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

    Uninstalling pytz-2024.2:
      Successfully uninstalled pytz-2024.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/62 [schema]

   ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/62 [pytz]

  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.9.3
   ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/62 [pytz]

    Uninstalling antlr4-python3-runtime-4.9.3:
      Successfully uninstalled antlr4-python3-runtime-4.9.3
   ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/62 [pytz]

   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]

  Attempting uninstall: zipp
   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]

    Found existing installation: zipp 4.1.0
    Uninstalling zipp-4.1.0:
      Successfully uninstalled zipp-4.1.0
   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]

  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.20
    Uninstalling urllib3-1.26.20:
      Successfully uninstalled urllib3-1.26.20
   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/62 [urllib3]

  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

      Successfully uninstalled typing_extensions-4.16.0
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.68.4
    Uninstalling tqdm-4.68.4:
      Successfully uninstalled tqdm-4.68.4
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

  Attempting uninstall: tblib
    Found existing installation: tblib 3.2.2
    Uninstalling tblib-3.2.2:
      Successfully uninstalled tblib-3.2.2
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]

  Attempting uninstall: smdebug-rulesconfig
    Found existing installation: smdebug-rulesconfig 1.0.1
    Uninstalling smdebug-rulesconfig-1.0.1:
      Successfully uninstalled smdebug-rulesconfig-1.0.1
   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/62 [smdebug-rulesconfig]

  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/62 [smdebug-rulesconfig]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

      Successfully uninstalled six-1.17.0
  Attempting uninstall: rpds-py
   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

    Found existing installation: rpds-py 0.27.1
    Uninstalling rpds-py-0.27.1:
      Successfully uninstalled rpds-py-0.27.1
  Attempting uninstall: pyyaml
   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]

    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/62 [pyyaml]

  Attempting uninstall: pygments
    Found existing installation: Pygments 2.20.0
   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/62 [pyyaml]

    Uninstalling Pygments-2.20.0:
      Successfully uninstalled Pygments-2.20.0
   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/62 [pyyaml]

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]

  Attempting uninstall: psutil
   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]

    Found existing installation: psutil 5.9.8
    Uninstalling psutil-5.9.8:
      Successfully uninstalled psutil-5.9.8
   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]

  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.31.1
    Uninstalling protobuf-6.31.1:
      Successfully uninstalled protobuf-6.31.1
   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]

  Attempting uninstall: platformdirs
    Found existing installation: platformdirs 4.10.0
    Uninstalling platformdirs-4.10.0:
      Successfully uninstalled platformdirs-4.10.0
   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]

  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
   ━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/62 [platformdirs]

    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
   ━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/62 [platformdirs]

  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
   ━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/62 [platformdirs]

    Uninstalling numpy-1.26.4:
   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

      Successfully uninstalled numpy-1.26.4
   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

  Attempting uninstall: mock
   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

    Found existing installation: mock 4.0.3
    Uninstalling mock-4.0.3:
      Successfully uninstalled mock-4.0.3
  Attempting uninstall: mdurl
   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19/62 [numpy]

    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: jmespath
    Found existing installation: jmespath 1.1.0
   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━ 22/62 [jmespath]

    Uninstalling jmespath-1.1.0:
      Successfully uninstalled jmespath-1.1.0
  Attempting uninstall: idna
    Found existing installation: idna 3.18
   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━ 22/62 [jmespath]

    Uninstalling idna-3.18:
      Successfully uninstalled idna-3.18
   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━ 22/62 [jmespath]

  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
   ━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━ 24/62 [h11]

      Successfully uninstalled h11-0.16.0
  Attempting uninstall: graphql-core
    Found existing installation: graphql-core 3.2.11
   ━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━ 24/62 [h11]

    Uninstalling graphql-core-3.2.11:
      Successfully uninstalled graphql-core-3.2.11
   ━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━ 24/62 [h11]

   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 25/62 [graphql-core]

  Attempting uninstall: dill
   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 25/62 [graphql-core]

    Found existing installation: dill 0.4.1
    Uninstalling dill-0.4.1:
      Successfully uninstalled dill-0.4.1
   ━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━ 26/62 [dill]

  Attempting uninstall: cloudpickle
   ━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━ 26/62 [dill]

    Found existing installation: cloudpickle 3.1.2
    Uninstalling cloudpickle-3.1.2:
      Successfully uninstalled cloudpickle-3.1.2
  Attempting uninstall: click
   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/62 [click]

    Found existing installation: click 8.2.1
    Uninstalling click-8.2.1:
      Successfully uninstalled click-8.2.1
   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/62 [click]

  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.9
    Uninstalling charset-normalizer-3.4.9:
      Successfully uninstalled charset-normalizer-3.4.9
   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/62 [click]

   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 29/62 [charset_normalizer]

  Attempting uninstall: certifi
    Found existing installation: certifi 2026.6.17
    Uninstalling certifi-2026.6.17:
      Successfully uninstalled certifi-2026.6.17
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 29/62 [charset_normalizer]

    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 29/62 [charset_normalizer]

  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.7.0
    Uninstalling annotated-types-0.7.0:
      Successfully uninstalled annotated-types-0.7.0
  Attempting uninstall: annotated-doc
   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 32/62 [annotated-types]

    Found existing installation: annotated-doc 0.0.4
    Uninstalling annotated-doc-0.0.4:
      Successfully uninstalled annotated-doc-0.0.4
  Attempting uninstall: uvicorn
    Found existing installation: uvicorn 0.51.0
   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 32/62 [annotated-types]

    Uninstalling uvicorn-0.51.0:
      Successfully uninstalled uvicorn-0.51.0
   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 32/62 [annotated-types]

   ━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 34/62 [uvicorn]

  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.2
    Uninstalling typing-inspection-0.4.2:
      Successfully uninstalled typing-inspection-0.4.2
   ━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 34/62 [uvicorn]

  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
   ━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 34/62 [uvicorn]

  Attempting uninstall: referencing
   ━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 36/62 [requests]

    Found existing installation: referencing 0.37.0
    Uninstalling referencing-0.37.0:
      Successfully uninstalled referencing-0.37.0
   ━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 36/62 [requests]

  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
   ━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 36/62 [requests]

      Successfully uninstalled python-dateutil-2.9.0.post0
   ━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 36/62 [requests]

  Attempting uninstall: pydantic-core
   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━ 38/62 [python-dateutil]

    Found existing installation: pydantic_core 2.46.4
    Uninstalling pydantic_core-2.46.4:
      Successfully uninstalled pydantic_core-2.46.4
   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━ 38/62 [python-dateutil]

  Attempting uninstall: omegaconf
   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━ 38/62 [python-dateutil]

    Found existing installation: omegaconf 2.3.0
    Uninstalling omegaconf-2.3.0:
      Successfully uninstalled omegaconf-2.3.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 40/62 [omegaconf]

  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.19
    Uninstalling multiprocess-0.70.19:
      Successfully uninstalled multiprocess-0.70.19
   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 40/62 [omegaconf]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 41/62 [multiprocess]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 41/62 [multiprocess]

  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 4.2.0
    Uninstalling markdown-it-py-4.2.0:
      Successfully uninstalled markdown-it-py-4.2.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 41/62 [multiprocess]

  Attempting uninstall: importlib-metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 41/62 [multiprocess]

    Found existing installation: importlib-metadata 6.10.0
    Uninstalling importlib-metadata-6.10.0:
      Successfully uninstalled importlib-metadata-6.10.0
  Attempting uninstall: graphql-relay
    Found existing installation: graphql-relay 3.2.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 43/62 [importlib-metadata]

    Uninstalling graphql-relay-3.2.0:
      Successfully uninstalled graphql-relay-3.2.0
  Attempting uninstall: google-pasta
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 43/62 [importlib-metadata]

    Found existing installation: google-pasta 0.2.0
    Uninstalling google-pasta-0.2.0:
      Successfully uninstalled google-pasta-0.2.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 43/62 [importlib-metadata]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━ 45/62 [google-pasta]

  Attempting uninstall: anyio
    Found existing installation: anyio 4.14.1
    Uninstalling anyio-4.14.1:
      Successfully uninstalled anyio-4.14.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━ 45/62 [google-pasta]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 46/62 [anyio]

  Attempting uninstall: starlette
    Found existing installation: starlette 0.52.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 46/62 [anyio]

    Uninstalling starlette-0.52.1:
      Successfully uninstalled starlette-0.52.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 46/62 [anyio]

  Attempting uninstall: rich
    Found existing installation: rich 14.3.4
    Uninstalling rich-14.3.4:
      Successfully uninstalled rich-14.3.4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 47/62 [starlette]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 48/62 [rich]

  Attempting uninstall: pydantic
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 48/62 [rich]

    Found existing installation: pydantic 2.13.4
    Uninstalling pydantic-2.13.4:
      Successfully uninstalled pydantic-2.13.4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 48/62 [rich]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 49/62 [pydantic]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 49/62 [pydantic]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 50/62 [pathos]

  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 50/62 [pathos]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

    Uninstalling pandas-2.3.3:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

      Successfully uninstalled pandas-2.3.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 51/62 [pandas]

  Attempting uninstall: jsonschema-specifications
    Found existing installation: jsonschema-specifications 2025.9.1
    Uninstalling jsonschema-specifications-2025.9.1:
      Successfully uninstalled jsonschema-specifications-2025.9.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 52/62 [jsonschema-specifications]

  Attempting uninstall: graphene
    Found existing installation: graphene 3.4.3
    Uninstalling graphene-3.4.3:
      Successfully uninstalled graphene-3.4.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 52/62 [jsonschema-specifications]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 53/62 [graphene]

  Attempting uninstall: docker
    Found existing installation: docker 7.1.0
    Uninstalling docker-7.1.0:
      Successfully uninstalled docker-7.1.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 53/62 [graphene]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 54/62 [docker]

  Attempting uninstall: botocore
    Found existing installation: botocore 1.43.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 54/62 [docker]

    Uninstalling botocore-1.43.0:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

      Successfully uninstalled botocore-1.43.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

  Attempting uninstall: s3transfer
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

    Found existing installation: s3transfer 0.17.1
    Uninstalling s3transfer-0.17.1:
      Successfully uninstalled s3transfer-0.17.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 55/62 [botocore]

  Attempting uninstall: jsonschema
    Found existing installation: jsonschema 4.23.0
    Uninstalling jsonschema-4.23.0:
      Successfully uninstalled jsonschema-4.23.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━ 57/62 [jsonschema]

  Attempting uninstall: fastapi
    Found existing installation: fastapi 0.139.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 58/62 [fastapi]

    Uninstalling fastapi-0.139.0:
      Successfully uninstalled fastapi-0.139.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 58/62 [fastapi]

  Attempting uninstall: boto3
    Found existing installation: boto3 1.43.0
    Uninstalling boto3-1.43.0:
      Successfully uninstalled boto3-1.43.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 58/62 [fastapi]

  Attempting uninstall: sagemaker-core
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 58/62 [fastapi]

    Found existing installation: sagemaker-core 2.15.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 60/62 [sagemaker-core]

    Uninstalling sagemaker-core-2.15.0:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 60/62 [sagemaker-core]

      Successfully uninstalled sagemaker-core-2.15.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 60/62 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 60/62 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 60/62 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 60/62 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 61/62 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 61/62 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 61/62 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 61/62 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 61/62 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 61/62 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62/62 [sagemaker]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-multimodal 1.5.0 requires nvidia-ml-py3<8.0,>=7.352.0, which is not installed.
autogluon-timeseries 1.5.0 requires chronos-forecasting<2.4,>=2.2.2, which is not installed.
autogluon-timeseries 1.5.0 requires einops<1,>=0.7, which is not installed.
autogluon-timeseries 1.5.0 requires peft<0.18,>=0.13.0, which is not installed.
dash 2.18.1 requires dash-core-components==2.0.0, which is not installed.
dash 2.18.1 requires dash-html-components==2.0.0, which is not installed.
dash 2.18.1 requires dash-table==5.0.0, which is not installed.
skops 0.14.0 requires prettytable>=3.9, which is not installed.
aiobotocore 3.7.0 requires botocore<1.43.1,>=1.42.90, but you have botocore 1.43.62 which is incompatible.
amazon-sagemaker-sql-editor 0.2.6 requires rpds-py==0.27.1, but you have rpds-py 2026.6.3 which is incompatible.
amazon-sagemaker-sql-magic 0.1.4 requires numpy<2, but you have numpy 2.5.1 which is incompatible.
autogluon-common 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.5.1 which is incompatible.
autogluon-common 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.5 which is incompatible.
autogluon-common 1.5.0 requires psutil<7.2.0,>=5.7.3, but you have psutil 7.2.2 which is incompatible.
autogluon-common 1.5.0 requires pyarrow<21.0.0,>=7.0.0, but you have pyarrow 21.0.0 which is incompatible.
autogluon-core 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.5.1 which is incompatible.
autogluon-core 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.5 which is incompatible.
autogluon-features 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.5.1 which is incompatible.
autogluon-features 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.5 which is incompatible.
autogluon-multimodal 1.5.0 requires fsspec[http]<=2025.3, but you have fsspec 2026.6.0 which is incompatible.
autogluon-multimodal 1.5.0 requires jsonschema<4.24,>=4.18, but you have jsonschema 4.26.0 which is incompatible.
autogluon-multimodal 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.5.1 which is incompatible.
autogluon-multimodal 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.5 which is incompatible.
autogluon-tabular 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.5.1 which is incompatible.
autogluon-tabular 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.5 which is incompatible.
autogluon-timeseries 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.5.1 which is incompatible.
autogluon-timeseries 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.5 which is incompatible.
autovizwidget 0.23.0 requires pandas<3.0.0, but you have pandas 3.0.5 which is incompatible.
catboost 1.2.7 requires numpy<2.0,>=1.16.0, but you have numpy 2.5.1 which is incompatible.
dash 2.18.1 requires Flask<3.1,>=1.0.4, but you have flask 3.1.3 which is incompatible.
dash 2.18.1 requires Werkzeug<3.1, but you have werkzeug 3.1.8 which is incompatible.
fugue 0.9.7 requires pandas<3, but you have pandas 3.0.5 which is incompatible.
gluonts 0.16.2 requires numpy<2.2,>=1.16, but you have numpy 2.5.1 which is incompatible.
gluonts 0.16.2 requires pandas<3,>=1.0, but you have pandas 3.0.5 which is incompatible.
hdijupyterutils 0.23.0 requires pandas<3.0.0, but you have pandas 3.0.5 which is incompatible.
jupyter-scheduler 2.12.0 requires psutil~=5.9, but you have psutil 7.2.2 which is incompatible.
jupyter-scheduler 2.12.0 requires pytz<=2024.2,>=2023.3, but you have pytz 2026.3.post1 which is incompatible.
mlflow 3.13.0 requires pandas<3, but you have pandas 3.0.5 which is incompatible.
numba 0.65.1 requires numpy<2.5,>=1.22, but you have numpy 2.5.1 which is incompatible.
opensearch-py 2.5.0 requires urllib3<2,>=1.26.18, but you have urllib3 2.7.0 which is incompatible.
sagemaker-mlops 1.12.0 requires sagemaker-core>=2.12.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-serve 1.12.0 requires sagemaker-core>=2.12.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-studio 1.1.22 requires numpy<2.3.0,>=1.26.4, but you have numpy 2.5.1 which is incompatible.
sagemaker-studio 1.1.22 requires pandas<3.0.0,>=2.3.2, but you have pandas 3.0.5 which is incompatible.
sagemaker-studio-analytics-extension 0.3.0 requires sparkmagic==0.22.0, but you have sparkmagic 0.21.0 which is incompatible.
sagemaker-train 1.14.0 requires sagemaker-core>=2.14.0, but you have sagemaker-core 1.0.78 which is incompatible.
sparkmagic 0.21.0 requires pandas<2.0.0,>=0.17.1, but you have pandas 3.0.5 which is incompatible.

Successfully installed annotated-doc-0.0.5 annotated-types-0.8.0 antlr4-python3-runtime-4.9.3 anyio-4.14.2 attrs-25.4.0 boto3-1.43.62 botocore-1.43.62 certifi-2026.7.22 charset_normalizer-3.4.9 click-8.4.2 cloudpickle-3.1.2 dill-0.4.1 docker-7.2.0 fastapi-0.141.1 google-pasta-0.2.0 graphene-3.4.3 graphql-core-3.2.11 graphql-relay-3.2.0 h11-0.16.0 idna-3.18 importlib-metadata-6.11.0 jmespath-1.1.0 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 markdown-it-py-4.2.0 mdurl-0.1.2 mock-4.0.3 multiprocess-0.70.19 numpy-2.5.1 omegaconf-2.3.1 packaging-24.2 pandas-3.0.5 pathos-0.3.5 platformdirs-4.11.0 pox-0.3.7 ppft-1.7.8 protobuf-6.33.6 psutil-7.2.2 pydantic-2.13.4 pydantic-core-2.46.4 pygments-2.20.0 python-dateutil-2.9.0.post0 pytz-2026.3.post1 pyyaml-6.0.3 referencing-0.37.0 requests-2.34.2 rich-14.3.4 rpds-py-2026.6.3 s3transfer-0.19.2 sagemaker-2.257.5 sagemaker-core-1.0.78 schema-0.7.8 six-1.17.0 smdebug-rulesconfig-1.0.1 starlette-1.3.1 tblib-3.2.2 tqdm-4.70.0 typing-extensions-4.16.0 typing-inspection-0.4.2 urllib3-2.7.0 uvicorn-0.52.0 zipp-4.1.0

Note: you may need to restart the kernel to use updated packages.

## 0. Configuration

Edit the values in this cell. Everything else references these variables.

In [2]:
import sagemaker, boto3

session = sagemaker.Session()
role    = sagemaker.get_execution_role()
region  = boto3.Session().region_name

TEAM_ID = "team03"
STUDENT_ID = "s301"

BUCKET = "nyp-26s1-iti113"
PROJECT_NAME = "crypto-scam-detector"
PREFIX = f"iti113/{TEAM_ID}/data/{PROJECT_NAME}"  # matches the PREFIX pattern used in Notebook 02

RANDOM_STATE = 42   # matches utils/preprocessing.py's default, kept identical so results match your Mac runs
TEST_SIZE    = 0.20 # matches utils/preprocessing.py's default

print(f"Bucket     : {BUCKET}")
print(f"Prefix     : {PREFIX}")
print(f"Region     : {region}")
print(f"Role       : {role.split('/')[-1]}")
print(f"Team ID    : {TEAM_ID}")
print(f"Student ID : {STUDENT_ID}")

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml

sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

/opt/conda/lib/python3.12/site-packages/sagemaker/__init__.py:86: SageMakerV2DeprecationWarning: You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation()
You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.

Bucket     : nyp-26s1-iti113
Prefix     : iti113/team03/data/crypto-scam-detector
Region     : ap-southeast-1
Role       : SageMakerExecutionRole-ITI113-Team03
Team ID    : team03
Student ID : s301

## 1. Load Dataset

**ADAPTED:** the tutor's version downloads the UCI Heart Disease dataset from a public URL, then uploads it to S3 for version control. This project's raw dataset doesn't have an equivalent no-auth public URL, so `kagglehub` downloads it directly from Kaggle instead -- this avoids depending on a local repo checkout of `data/crypto_scam_dataset.csv`, which matters in SageMaker Studio (no repo clone here). This cell checks S3 first and loads from there if the raw file already exists (`{PREFIX}/raw/crypto_scam_dataset.csv`); only on the very first run anywhere does it fall back to `kagglehub` and upload the result -- so every run after that, on any machine, reads from S3 instead of re-fetching from Kaggle each time.

| Column | Description |
|--------|-------------|
| id | Unique message identifier |
| platform | Source platform (Telegram, X/Twitter, SMS, Email, Discord, Reddit) |
| text | Message content |
| label | `scam` or `legit` |

In [3]:
import io
import os

import kagglehub
import pandas as pd

s3 = boto3.client('s3')
RAW_S3_KEY = f'{PREFIX}/raw/crypto_scam_dataset.csv'
RAW_S3_URI = f's3://{BUCKET}/{RAW_S3_KEY}'

try:
    obj = s3.get_object(Bucket=BUCKET, Key=RAW_S3_KEY)
    df_raw = pd.read_csv(io.BytesIO(obj['Body'].read()))
    print(f'Loaded raw dataset from S3: {RAW_S3_URI}')
except s3.exceptions.NoSuchKey:
    dataset_path = kagglehub.dataset_download("theeyanyan/crypto-scam-dataset")
    csv_file = os.path.join(dataset_path, "crypto_scam_dataset.csv")
    df_raw = pd.read_csv(csv_file)

    buf = io.StringIO()
    df_raw.to_csv(buf, index=False)
    s3.put_object(Bucket=BUCKET, Key=RAW_S3_KEY, Body=buf.getvalue())
    print(f'Not yet in S3 -- downloaded via kagglehub and uploaded to: {RAW_S3_URI}')

print(f'Shape : {df_raw.shape}')
print(f'Label : {df_raw["label"].value_counts().to_dict()}')
df_raw.head()

Loaded raw dataset from S3: s3://nyp-26s1-iti113/iti113/team03/data/crypto-scam-detector/raw/crypto_scam_dataset.csv
Shape : (10000, 4)
Label : {'scam': 5500, 'legit': 4500}

   id  platform                                               text  label
0   1     Email  Following up on your recovery request for wall...   scam
1   2       SMS  Does anyone have a good resource for understan...  legit
2   3  Telegram  The MetaSwap team posted a security disclosure...  legit
3   4  Telegram  Been dollar-cost averaging into ETH for about ...  legit
4   5       SMS  Your account requires immediate verification d...   scam

## 2. Exploratory Data Analysis

**Placeholder — Royston's section (Focus A).** The Progress Check rubric wants completed EDA with insights and patterns identified here: missing-value checks (none, per the load above, but worth confirming), class balance (`scam` vs `legit`), platform distribution, message length distribution, common scam-language patterns, and any data-quality issues or bias observations for the AI Governance checklist. Left empty intentionally rather than filled in on his behalf — see `df_raw` from Section 1 above as the starting point.

## 3. Feature Engineering & Preprocessing

**ADAPTED — now fully inline**, matching the tutor's own notebook (their `age_group`/`high_risk_count` engineering, split, and `StandardScaler` are inline too, specific to the tabular heart-disease features). This project's text data needs different steps instead: text cleaning, the proposal's engineered indicator features (urgency, contact/link, structural characteristics), a stratified train/test split, and TF-IDF fitting — written inline here rather than imported from `utils/preprocessing.py`, so this notebook runs standalone with no repo clone / `utils` import required. No feature scaling is applied, matching the rest of the project (TF-IDF features aren't scaled elsewhere either).

In [4]:
# Step 1: clean text (mirrors utils/preprocessing.py's clean_text())
import re

URL_PATTERN = re.compile(r"https?://[^\s]+|www\.[^\s]+")

def clean_text(text: str) -> str:
    """Normalise raw message text before TF-IDF vectorisation."""
    if not isinstance(text, str):
        return ""
    text = text.strip()
    text = URL_PATTERN.sub(" <url> ", text)
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df = df_raw.copy()
df["clean_text"] = df["text"].apply(clean_text)
df[["text", "clean_text"]].head()

,text,clean_text
0,Following up on your recovery request for wall...,following up on your recovery request for wall...
1,Does anyone have a good resource for understan...,does anyone have a good resource for understan...
2,The MetaSwap team posted a security disclosure...,the metaswap team posted a security disclosure...
3,Been dollar-cost averaging into ETH for about ...,been dollar-cost averaging into eth for about ...
4,Your account requires immediate verification d...,your account requires immediate verification d...

In [5]:
# Step 2: engineered indicator features (mirrors utils/indicators.py + utils/preprocessing.py)
# Keyword lists come straight from the project proposal's indicator design.
URGENT_KEYWORDS = [
    "urgent", "immediately", "act now", "act fast", "hurry", "limited time",
    "today only", "expires today", "offer ends soon", "last chance",
    "don't miss out", "within 24 hours", "within 1 hour", "respond now",
    "claim now", "limited slots", "before it's too late", "time-sensitive",
]
GUARANTEED_RETURN_KEYWORDS = [
    "guaranteed return", "guaranteed returns", "guaranteed profit",
    "risk-free", "risk free", "100% profit", "double your money",
    "high returns", "\u7a33\u8d5a\u4e0d\u8d54",
]
PAYMENT_KEYWORDS = [
    "deposit", "transfer funds", "send payment", "pay now", "top up",
    "bitcoin", "btc", "ethereum", "eth", "usdt", "wallet address",
]
OFF_PLATFORM_KEYWORDS = [
    "telegram", "whatsapp", "discord", "wechat", "private chat",
    "dm me", "direct message",
]
CREDENTIAL_KEYWORDS = [
    "seed phrase", "private key", "wallet password", "recovery phrase",
    "otp", "verification code", "security code",
]

WALLET_PATTERN = re.compile(r"\b(?:0x[a-fA-F0-9]{40}|[13][a-km-zA-HJ-NP-Z1-9]{25,34})\b")
EMAIL_PATTERN = re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}")
PHONE_PATTERN = re.compile(r"(?:\+?\d[\d\s-]{7,}\d)")
COUNTDOWN_PATTERN = re.compile(r"\b\d+\s*(?:hour|hours|hr|hrs|minute|minutes|min|mins|day|days)\b", re.IGNORECASE)

def find_keyword_matches(message: str, keywords: list) -> list:
    message_lower = message.lower()
    return [k for k in keywords if k.lower() in message_lower]

def extract_engineered_features(text: str) -> dict:
    if not isinstance(text, str):
        text = ""

    urgency_keyword_hits = len(find_keyword_matches(text, URGENT_KEYWORDS))
    guaranteed_return_hits = len(find_keyword_matches(text, GUARANTEED_RETURN_KEYWORDS))
    countdown_hits = len(COUNTDOWN_PATTERN.findall(text))
    exclamation_count = text.count("!")
    urgency_score = urgency_keyword_hits + countdown_hits + min(exclamation_count, 3)

    wallet_matches = WALLET_PATTERN.findall(text)
    url_matches = URL_PATTERN.findall(text)
    email_matches = EMAIL_PATTERN.findall(text)
    phone_matches = PHONE_PATTERN.findall(text)
    payment_hits = len(find_keyword_matches(text, PAYMENT_KEYWORDS))
    off_platform_hits = len(find_keyword_matches(text, OFF_PLATFORM_KEYWORDS))
    credential_hits = len(find_keyword_matches(text, CREDENTIAL_KEYWORDS))

    letters = [c for c in text if c.isalpha()]
    capital_ratio = sum(1 for c in letters if c.isupper()) / len(letters) if letters else 0.0
    digit_count = sum(1 for c in text if c.isdigit())

    return {
        "urgency_keyword_count": urgency_keyword_hits,
        "guaranteed_return_keyword_count": guaranteed_return_hits,
        "countdown_phrase_count": countdown_hits,
        "exclamation_count": exclamation_count,
        "urgency_score": urgency_score,
        "has_wallet_address": int(bool(wallet_matches)),
        "wallet_address_count": len(wallet_matches),
        "has_url": int(bool(url_matches)),
        "url_count": len(url_matches),
        "has_email": int(bool(email_matches)),
        "has_phone_number": int(bool(phone_matches)),
        "payment_keyword_count": payment_hits,
        "off_platform_keyword_count": off_platform_hits,
        "credential_keyword_count": credential_hits,
        "message_length": len(text),
        "capital_letter_ratio": round(capital_ratio, 4),
        "has_numeric_content": int(digit_count > 0),
        "digit_count": digit_count,
    }

engineered = pd.DataFrame([extract_engineered_features(t) for t in df["text"]], index=df.index)
ENGINEERED_COLS = list(engineered.columns)
df = pd.concat([df, engineered], axis=1)
df[ENGINEERED_COLS].head()

,urgency_keyword_count,guaranteed_return_keyword_count,countdown_phrase_count,exclamation_count,urgency_score,has_wallet_address,wallet_address_count,has_url,url_count,has_email,has_phone_number,payment_keyword_count,off_platform_keyword_count,credential_keyword_count,message_length,capital_letter_ratio,has_numeric_content,digit_count
0,1,0,1,0,2,1,2,0,0,0,1,1,0,0,292,0.0370,1,61
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,212,0.0412,1,4
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,176,0.0284,0,0
3,0,0,0,0,0,0,0,0,0,0,1,1,0,0,286,0.0327,1,12
4,2,0,1,0,3,0,0,0,0,1,0,0,0,0,220,0.0718,1,3

In [6]:
# Step 3: train/test split (stratified on label)
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=df["label"],
)

print(f'Train: {train_df.shape[0]} rows  |  Test: {test_df.shape[0]} rows')
print(f'Train label balance: {(train_df["label"]=="scam").mean():.3f}  '
      f'(full dataset: {(df_raw["label"]=="scam").mean():.3f})')
print(f'Test  label balance: {(test_df["label"]=="scam").mean():.3f}  (stratification confirmed)')

Train: 8000 rows  |  Test: 2000 rows
Train label balance: 0.550  (full dataset: 0.550)
Test  label balance: 0.550  (stratification confirmed)

In [7]:
# Step 4: fit TF-IDF vectorizer -- IMPORTANT: fit on TRAIN text only, never on test
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2), min_df=2)
vectorizer.fit(train_df["clean_text"])

print(f'TF-IDF vocabulary size: {len(vectorizer.get_feature_names_out())}')

TF-IDF vocabulary size: 5000

## 4. Save Processed Data to S3

In [8]:
# ADAPTED: the tutor's version saves four numeric CSVs (train/test features and labels
# split apart), which fits tabular data. This project's processed output is train_df /
# test_df (text + engineered features + label together, matching data/processed/*.csv
# already produced locally) plus the fitted TF-IDF vectorizer -- so three artifacts are
# uploaded instead. If Notebook 02/03 are later switched to load from S3 instead of
# re-running the pipeline locally, they should read these three, not the tutor's four.

import joblib
import tempfile

def save_csv_to_s3(df, bucket, key):
    buf = io.StringIO()
    df.to_csv(buf, index=False)
    s3.put_object(Bucket=bucket, Key=key, Body=buf.getvalue())
    return f's3://{bucket}/{key}'

def save_joblib_to_s3(obj, bucket, key):
    with tempfile.NamedTemporaryFile(suffix='.joblib') as tmp:
        joblib.dump(obj, tmp.name)
        s3.upload_file(tmp.name, bucket, key)
    return f's3://{bucket}/{key}'

p = f'{PREFIX}/processed'
paths = {
    'train'            : save_csv_to_s3(train_df, BUCKET, f'{p}/train.csv'),
    'test'             : save_csv_to_s3(test_df, BUCKET, f'{p}/test.csv'),
    'tfidf_vectorizer' : save_joblib_to_s3(vectorizer, BUCKET, f'{p}/tfidf_vectorizer.joblib'),
}
for name, uri in paths.items():
    print(f'{name:<20}: {uri}')

PROCESSED_PREFIX = f's3://{BUCKET}/{p}'
print(f'\nProcessed prefix: {PROCESSED_PREFIX}')
print('Next: open Notebook 02 to run baseline experiments with MLflow.')

train               : s3://nyp-26s1-iti113/iti113/team03/data/crypto-scam-detector/processed/train.csv
test                : s3://nyp-26s1-iti113/iti113/team03/data/crypto-scam-detector/processed/test.csv
tfidf_vectorizer    : s3://nyp-26s1-iti113/iti113/team03/data/crypto-scam-detector/processed/tfidf_vectorizer.joblib

Processed prefix: s3://nyp-26s1-iti113/iti113/team03/data/crypto-scam-detector/processed
Next: open Notebook 02 to run baseline experiments with MLflow.

---
## Checklist before Notebook 02

- [ ] Raw dataset uploaded to S3
- [ ] EDA completed by Royston (Section 2) — insights, class balance, platform distribution, data quality / bias observations for AI Governance
- [ ] Data pipeline run successfully (inline, no `utils` import) — clean text, engineered indicator features, TF-IDF fitted, stratified train/test split
- [ ] Processed train/test data and TF-IDF vectorizer saved to S3
- [ ] EDA observations and governance flags documented for the checklist